name: Flask CI/CD with Docker

on:
  push:
    branches:
      - main

env:
  AZURE_REGISTRY_NAME: OcProjectSeven    # Set this to your Azure Container Registry's name without the domain suffix
  AZURE_WEBAPP_NAME: p7-api
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  PYTHON_VERSION: '3.11'
  DOCKER_IMAGE_NAME: p7-api-image   # Name of your Docker image, adjust as needed
  DOCKER_IMAGE_TAG: latest          # Tag for your Docker image, adjust as needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main

    - name: Set up Python version
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: 'Install Requirements'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 'Run Tests'
      run: |
        pytest

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Build and Push Docker Image to ACR'
      run: |
        az acr build --image ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }} --registry ${{ env.AZURE_REGISTRY_NAME }} --file Dockerfile ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    # You can add further steps here if you wish to deploy this Docker image somewhere.
